name: Triton
version: ${project.version}
main: com.rexcantor64.triton.loader.SpigotLoader
api-version: 1.13
description: "A plugin that replaces any message on your server, to the receiver's language, in real time!"
author: Rexcantor64
website: https://triton.rexcantor64.com/
softdepend: [PlaceholderAPI]
folia-supported: true

commands:
  twin:
    description: Upload and download your config to/from the Triton Web INterface.
    usage: "/twin [code]"

permissions:
  triton.getflag:
    default: op
  triton.setlanguage:
    default: true
  triton.setlanguage.others:
    default: op
  triton.openselector:
    default: true
  triton.reload:
    default: op
  triton.help:
    default: true
  triton.sign:
    default: op
  triton.database:
    default: op
  triton.info:
    default: true
  triton.loglevel:
    default: op
  twin.upload:
    default: op
  twin.download:
    default: op
